<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;
use Ramsey\Uuid\UuidInterface;

/**
 * TodoRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TodoRepository extends EntityRepository
{
    public function persist(Todo $todo)
    {
        $em = $this->getEntityManager();
        $em->persist($todo);
        $em->flush();
    }

    public function delete(UuidInterface $applicationId, UuidInterface $id)
    {
        $this->createQueryBuilder('t')
            ->delete()
            ->where('t.applicationId = :applicationId')
            ->andWhere('t.id = :id')
            ->setParameter('id', $id)
            ->setParameter('applicationId', $applicationId)
            ->getQuery()
            ->execute();
    }

    public function forApplication(UuidInterface $applicationId)
    {
        return $this->createQueryBuilder('t')
            ->where('t.applicationId = :applicationId')
            ->setParameter('applicationId', $applicationId)
            ->getQuery()
            ->getResult();
    }
}
